export const GET_LIST = 'GET_LIST';
export const GET_LIST_FOR_NAME = "GET_LIST_FOR_NAME"
export const GET_LIST_FOR_ID = "GET_LIST_FOR_ID"
export const LOADING = "LOADING";

export const FILTER_FOR_NAME_DESCENDENT='FILTER_FOR_NAME_DESCENDENT'
export const FILTER_FOR_NAME_ASCENDENT = 'FILTER_FOR_NAME_ASCENDENT'
export const FILTER_FOR_LOW_SCORE = 'FILTER_FOR_LOW_SCORE';
export const FILTER_FOR_HIGH_SCORE = 'FILTER_FOR_HIGH_SCORE';
export const GET_DIETS = 'GET_DIETS'
export const GET_DIET_TYPES = 'GET_DIET_TYPES';
export const POST_RECIPE = "POST_RECIPE"

